### ISSUE TITLE
Add AirConsole to NPM

### ISSUE THREAD

**Issue by ehgoodenough** [AirConsole/airconsole-api#33]
I'd love to access the AirConsole API through NPM, the node package manager. A lot of devs use webpack or browserify to compile their javascript dependencies from NPM. Once the api has been registered with NPM, I can call `npm install airconsole` to get the latest version of the package. :]

**Comment by aspin** [comment]
+1 bower too

**Comment by FieryCod** [comment]
+1

**Comment by andrew-luminal** [comment]
👍

**Comment by met5678** [comment]
+1

**Comment by andrin-n-dream** [comment]
The problem with this is that you would self-host the API, which is against our policy.
If you self-host the API then we can't do hot fixes (very rare, but we want the ability to do this).
Therefor you should always include the api from https://www.airconsole/api/...
