### ISSUE TITLE
Anonymous caller does not have storage.objects.get access to com.airconsole.ads

### ISSUE THREAD

**Issue by joemicmc** [AirConsole/airconsole-api#54]
This issue was raised by a user on Twitter: https://twitter.com/FrostyForsyte/status/1052672661208350721

### Details

Browser: Chrome
Steps: Load game and trigger ad break

### Description

The ad doesn't load with error `Anonymous caller does not have storage.objects.get access to com.airconsole.ads.break.cdn.airconsole.com/2018-10-12-15-47-23/screen-content/table;.html.`

Screenshot from user:

![image](https://user-images.githubusercontent.com/7323103/47213970-75379e80-d394-11e8-82bb-0169e19f4885.png)

**Comment by francois-n-dream** [comment]
This is fixed - thank you!

**Comment by francois-n-dream** [comment]
This is fixed - thank you!

**Comment by joemicmc** [comment]
Thanks Francois!
