### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: BetterJsPop

### ISSUE THREAD

**Issue by joemicmc** [AirConsole/airconsole-api#56]
I think this is in the AirConsole API screen code, but not 100% sure. I don't think it's limited to Unity plugin so raised here.

### Details

Browser: Chrome on Mac
Source: `https://game.airconsole.com/net.eightbitape.dungeoncrawl.cdn.airconsole.com/2018-10-16-14-11-36/screen.html:20:10`
Error: `Uncaught TypeError: Cannot redefine property: BetterJsPop`

Stack trace:

    TypeError: Cannot redefine property: BetterJsPop
    at Function.defineProperty ()
    at inject (:20:10)
    at :510:11
    at :511:11

**Comment by francois-n-dream** [comment]
Thank you!
But this doesn't seem to be an AirConsole related issue.
Maybe it's thrown by an Ad blocker extension?!

**Comment by joemicmc** [comment]
Ah, was that from here: https://stackoverflow.com/questions/50272371/what-is-betterjspop-error-on-chrome

That would match the fact that error is only on Chrome!

**Comment by joemicmc** [comment]
Ah yeah, it looks like that could be the culprit. Something to keep in mind
if users report errors on screen I guess!

Regards,


*Joe Michael McDonald*
8bitape.net
joemichaelmcdonald.com
+44 (0) 7861379749
